### PR TITLE
External improvements

### PR DESCRIPTION
**Pull request by Xikaro**
:)

### CODE REVIEW

**Comment by Xikaro** [comment]
#162

**Comment by Xikaro** [comment]
Screenshot_352
Screenshot_353
with Gregtech installed, there will be a bloom effect

**Comment by Xikaro** [comment]
Screenshot_354

**Comment by PrototypeTrousers** [comment]
where are theses textures from?
is keeping the textures variables not possible ? i thought you were just adding bloom to the models, but that may break some resource packs people use

**Comment by Xikaro** [comment]
models should be fully compatible with the texture packs, except for the inside, the one I added, the bloom is fully compatible

**Comment by Xikaro** [comment]
texture of the inside from 1.18

**Comment by Xikaro** [comment]
Fixed the model, now it uses standard textures, and should not break texturepacks

**Pull request merged**
